import = [ "~/.config/alacritty/themes/themes/tokyo-night.toml" ]

[shell]
program = "/opt/homebrew/bin/tmux"

[window]
dimensions = { columns = 160, lines = 50 }

[font]
size = 15
normal = { family = "Mononoki Nerd Font"}


