import = [ "~/.config/alacritty/themes/themes/github_dark.toml" ]

[shell]
program = "tmux"

[window]
dimensions = { columns = 160, lines = 50 }

[font]
size = 15
#normal = { family = "Mononoki Nerd Font"}
normal = { family = "FreeMono"}


